Clever/heka-clever-plugins

.drone.yml, README.md, postgres/postgres.go, postgres/postgres_test.go, postgres_output.go
Issue: https://clever.atlassian.net/browse/INFRA-613
This output allows batching Heka messages into a bulk Postgres insert. We read field values from the message, and then write them into the query.
For example, you might receive a message like:
```
:Fields:
| name:"title" type:string value:"hello"
| name:"value" type:string value:5
```
You could then configure the table and fields to the write in heka toml: 
```
insert_table=my_table
insert_fields=title value
```
This will result in writing an INSERT like:
```
INSERT INTO "my_table" VALUES ($1, $2)
```
and later parametrizing them with "hello" and 5, i.e.
```
INSERT INTO "my_table" VALUES ("hello", 5)
```
It also supports batching Heka messages to insert multiple, batching on number of messages or ticker duration.
=> postgres_output: convert heka message into postgres INSERT

postgres/postgres.go, postgres/postgres_test.go, postgres_output.go
Context: https://clever.atlassian.net/browse/INFRA-613
Deployed this earlier and the writing was successful, but it caused too many connection errors. Made two improvements to mitigate this:
1. Close() `*sql.rows` - this was causing a connection leak before
2. Allow configuring maxOpenConnections
Also made changes to require writing to specific columns instead of writing values in-order into the table.
=> Infra 613 postgres output improvements

README.md, postgres_output.go
Previously, if the Heka message was missing a field, the insert
would always fail with an error.
Now, it's possible to do an insert with missing message fields, where a
NULL value will be written instead.
=> postgres_output: allow missing fields

lua/decoders/json_decoder.lua
- through trial and error, I figured out the max string buffer size is a
little over 11500 characters, so just throw things larger than that
away instead of crashing heka
=> enforce a maximum payload size for json decoder

mock_filter_runner_test.go, mock_output_runner_test.go
- heka 0.9.0 doesn't use PluginGlobals anymore
=> remove PluginGlobals:

postgres_output.go
**Why**: Around 2 week ago I released a new business metric script that would counted the number of authorized apps, teachers, and students for each district.  The script would printed all of its results (8k log lines) in less than a second.  As a result, the Postgres (and Influx) Heka outputs would quickly start reporting idle packets, which halted all Heka processing.
**What**: After much debugging, the root cause turned out to be two fold.  The first issue was that the postgres_output only maintained one batch at a time, which effectively meant that the output blocked on inserts.  The second issue was that occasionally postgres_output sent RedShift insert statements that would take more than 120 seconds to complete, which because of the first issue caused the output to block for over …
=> Fortify postgres_output

lua/filters/fieldfix.lua
As discussed in person.
With the following config:
```
[FieldFixFilter]
message_matcher = "Type == 'Kayvee'"
type = "SandboxFilter"
filename = "/heka/clever/filters/fieldfix.lua"
preserve_data = false
[FieldFixFilter.config]
fields_if_missing = "source=myhost target=remotehost"
fields_override = 'cluster="wibble" '
fields_remove = "product"
fields_interpolate = 'foobar="my_level: %{level}" hello=world'
[console_output]
type = "LogOutput"
message_matcher = "Type == 'heka.sandbox.fieldfix'"
encoder = "RstEncoder"
```
And the log line:
```
http://lua-users.org/wiki/RangeIterator
```
It produces:
```
:Timestamp: 2015-06-17 23:24:06.599616 +0000 UTC
:Type: heka.sandbox.fieldfix
:Hostname: 2c1932df705c
:Pid: 0
:Uuid: 4998fdc4-fa51-4f21-a918-9c4be44de5d2
:Logger: FieldFixFilter
:Payload: …
```
=> Add an interpolation filter.

lua/filters/fieldfix.lua
- added `payload` to the config, to allow rewriting its value. (It can't be rewritten like other fields)
- combined `fields_override` and `fields_interpolate`, since they are have same behavior just one interpolates. now only `fields_override` exists, and interpolate is just a feature
=> Fieldfix allow writing payload

lua/filters/signalfxbatch.lua
This matches the behavior defined in the comments 
https://github.com/Clever/heka-clever-plugins/blob/master/lua/filters/signalfxbatch.lua#L35
=> lua/filters: signalfx- default gauge value to 0

all_plugins_test.go, postgres/postgres.go, postgres_output.go
We were seeing errors of the form: `pq: there is no parameter $-32768` and `Postgres insert took more than 60000ms.`. This PR (tested in staging) increases the timeout for the queries and adds extra checks on the line that seemed to be the culprit for the `pq: there is no parameter $-32768` error.
=> IP-263: Longer timeout for queries  + extra check against int16 overflow

postgres_output.go
Lower default `flushCount` and ensure that params used in INSERT...VALUES don't cross the limit for Redshift
=> IP-263: ensure that params used in INSERT...VALUES don't cross the limit for Redshift

firehose_output.go, firehose_output_test.go
Quite a few of the event tables have timestamp in them, but the name of the timestamp column is not always the same. This allows the firehose config to specify a name for the timestamp column in Redshift.
=> INFRA-1175: allow setting timestamp column name through config

firehose_output.go, firehose_output_test.go
* we should always be using an encoder but backwards compatibility
* rather than the current way we should fall back to payload
* added check to not write anything to s3 if it's an empty object
=> firehose: use encoder if payload is not json

firehose_output.go, firehose_output_test.go
This PR covers two things:
1) adds batching support which is mostly copied from the elasticsearch output in `heka-private`.
2) Updates the plugin to use the `output` interface instead of the one for inputs
I've tested locally using heka-testing and have added a basic unittest.
=> INFRA-1438 Add batching support to firehose output

lua/filters/influxdbbatch9.lua, lua/filters/influxdblinebatch.lua
Ahem. Github now does not show the _move_ since files have diverged enough. 
* remove all excess code not required for InfluxDB line protocol
* simplify configuration
* separate functions for `field` and `tag` encoding
TODO: 
* sort `tags` before writing to string as InfluxDB docs say it gives better performance[1]
* (maybe) can we somehow deal with low resolution timestamps without resorting to internal counters?
[1]: [Tags should be sorted by key before being sent for best performance. The sort should match that from the Go bytes.Compare function (http://golang.org/pkg/bytes/#Compare).](https://docs.influxdata.com/influxdb/v0.12/write_protocols/line/)
=> InfluxDB Line Protocol: batch filter for heka

lua/encoders/slack.lua
written to preserve backwards compatibility.
Allows creating messages on the fly from heka messages.
My primary reason for writing this is https://clever.atlassian.net/browse/INFRA-1684
=> support field interpolation in slack

lua/filters/log_monitor.lua
Tested in `heka-testing` 
Related PRs:
- heka-testing: https://github.com/Clever/heka-testing/pull/64
- heka-outputs: https://github.com/Clever/heka-outputs/pull/97
- log-router: https://github.com/Clever/log-router/pull/31
**NOTE** This needs to be merged first so that the other repos can pull the latest version of `heka-clever-plugins`
=> Fix metric name and dimensions in log-monitor

lua/decoders/elasticsearch_rename_metafields_decoder.lua
According this page colons should be okay: http://grokbase.com/t/gg/elasticsearch/144s6e3877/illegal-characters-in-elasticsearch-field-names
cc @burnsed
=> Turns out elasticsearch v2.3 doesn't alllow  dots in fields name

batcher/message_batcher.go, batcher/message_batcher_test.go, kv_firehose_output.go
**Explanation**:
The goal was to eliminate the redundant configuration in the log-router and redshift heka-output.  Ultimately this was achieved by using a `fieldfix` filter in the log-router to embed the name of redshift stream into the message.  Example of the config:
```toml
[SyncEventsDistrictAppCountsFirehoseFilter]
type = "SandboxFilter"
filename = "/heka/clever/filters/fieldfix.lua"
preserve_data = false
message_matcher = "Type == 'Kayvee' && Fields[source] == 'space' && Fields[title] == 'events_from_sync'"
[SyncEventsDistrictAppCountsFirehoseFilter.config]
fields_if_missing = "_kvmeta.redshift.series=%ENV[FIREHOSE_EVENTS_DISTRICT_APP_COUNTS]"
```
As a result the number of outputs in the log-router and redshift heka-outputs was greatly reduced.  
Only a single AMQP output for …
=> Generalize redshift output

aws/firehose.go
Noticed a panic in prod: http://search-logs-v23-7qghqi2w3g6ywh4dhyoh32awia.us-west-2.es.amazonaws.com/_plugin/kibana/#/discover?_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:'2016-10-17T00:00:00.000Z',mode:absolute,to:'2016-10-17T00:30:00.000Z'))&_a=(columns:!(rawlog),filters:!(),index:%5Blogs-%5DYYYY.MM.DD,interval:auto,query:(query_string:(analyze_wildcard:!t,lowercase_expanded_terms:!f,query:'container_app:heka-outputs-redshift')),sort:!(Timestamp,desc))
This should fix it.
=> Added nil check to avoid panic

lua/decoders/kvmeta.lua, lua/decoders/kvmeta_spec.lua, lua/util.lua
Previously, it injected one message without any kvmeta.
Now, it's more explicit if it matches a message, and anything that's
routedb by kvmeta decoder will always have a `_kvmeta.type` field set.
=> kvmeta decoder now sets default 'logs' route

aws/firehose.go
There is a dereference in the firehouse output that sometimes causes panics.  I have tracked the panic down to this specific line.  Because the same `PutRecordBatchResponseEntry` is used for success and failure, sometimes `entry.Message` is nil.
You can see that this panic correlates very clearly to all of our crashes/imbalances by querying in kibana for `failed-record OR panic OR "firehose.go\:85"`
=> INFRA-2065 Fix a panic in the firehose output

lua/decoders/clever_container_decoder.lua, lua/decoders/clever_container_decoder_spec.lua
This PR allows logs to manually inject their own container_{app,env,task}.
=> allow overriding container_{app,env,task}

Makefile, lua/decoders/kvmeta.lua, lua/decoders/kvmeta_spec.lua
Previously, looked for routes array under `_kvmeta` top level key.
Now looks for `routes` inside kvmeta dict:
```json
{
"_kvmeta": {
"routes": [ ]
}
}
```
This is a fix due to a minor bug in how the spec was implemented.
cc @xavi- 
-- 
also includes a `Makefile` fix: https://github.com/Clever/heka-clever-plugins/pull/82/commits/2f6a52a34f9d3108247231a4ecd6ebbca135372d .. `lua-tests` wasn't returning an error properly because of using `;` vs `&&`
=> Kvmeta read from routes key

lua/filters/kayvee_influxdblinebatch.lua, lua/filters/kayvee_influxdblinebatch_spec.lua, lua/filters/kayvee_signalfxbatch.lua, lua/filters/kayvee_signalfxbatch_spec.lua
In the two real-world examples of people using the alerts output, neither used a proper `value` quantity, so it makes sense to add default values.
cc @nathanleiby
=> Set default values for influx and signalfx

lua/filters/kayvee_signalfxbatch.lua, lua/filters/kayvee_signalfxbatch_spec.lua
Currently, if a non-string dimension is passed, SignalFX will reject it
with a 400 error.
=> lua/filters: kayvee_signalfx- cast dimensions to strings

firehose_output.go
Right now the data we write to Firehose consists of consecutive JSON objects with no newlines separating them. This is inconvenient for analyzing the data when forwarded to S3 as the raw text.
At first I thought this might have an impact on Firehose outputs that forward to Redshift, but it appears as though the Redshift COPY operation does not require JSON objects to be newline separated: http://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-format.html#copy-json
=> add newlines to firehose output

lua/decoders/kvmeta.lua, lua/decoders/kvmeta_spec.lua
Issue: https://clever.atlassian.net/browse/INFRA-2174
This is for backwards compatibility. We don't want to accidentally break
existing log routing by moving to KvMeta routing. So let's keep
un-routed logs as `Kayvee` type and ignore their `_kvmeta`.
=> kvmeta: if no routes, treat as Kayvee

aws/firehose.go
Issue: https://clever.atlassian.net/browse/INFRA-2209
This is needed for kinesis consumer work.
=> aws/firehose: update to match newer AWS sdk interface
